# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: '@typescript-eslint/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
    groups:
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - '@typescript-eslint/*'
      vueuse:
        applies-to: version-updates
        patterns:
          - '@vueuse/*'
      minor-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 15
