name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18


          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - run: pip install setuptools
      - run: yarn install && yarn global add @quasar/cli
      - run: quasar build -m electron -P always


   #   - name: Build/release Electron app
  #    uses: samuelmeuli/action-electron-builder@v1
  #    with:
  #      github_token: ${{ secrets.github_token }}
  #      release: ${{ startsWith(github.ref, 'refs/tags/v') }}
